name: CI-CD

on:
  push:
    branches: ["main"]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.0
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v6.9.0
        with:
          context: ./src
          file: ./src/Dockerfile
          push: true
          tags:
            LucasMontesGarcia/kube-news:v1
            LucasMontesGarcia/kube-news:latest
          
      
